apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: k8s-demo-app
spec:
  replicas: 3
  template:
    metadata:
      name: k8s-demo-app
      labels:
        app: k8s-demo-app
    spec:
      containers:
      - image: mleitz1/k8s-demo-app:0.0.1-SNAPSHOT_arm32
        name: k8s-demo-app
